### ISSUE TITLE
Minor edits to your docs

### ISSUE THREAD

**Issue by florinme** [robmarshall/gatsby-gravityforms-component#1]
You reference `gatsby-gravityforms-components` (plural) several times in your readme, but It looks like your package is singular `npm i gatsby-gravityforms-component`

Thank you for this project! I'm trying to implement it now on a project, hopefully this will work otherwise I'll need to explore Netlify forms. If i had the luxury of time I'd help you out with this!

You also mention that `gatsby-plugin-compile-es6-packages` is included as a peer dependency, but it doesn't look like it is included. I had to install it separately.

**Comment by robmarshall** [comment]
Nice one. Corrected this!
