### ISSUE TITLE
Unknown Fields Error in fragments.js

### ISSUE THREAD

**Issue by adamcurl** [robmarshall/gatsby-gravityforms-component#24]
When I run a `gatsby develop`, I receive the following errors:

- `Unknown field 'subLabelPlacement' on type 'GF__Form'. Source: document 'GravityFormComponent' file: 'GraphQL request'`
- `Unknown field 'disableAutoformat' on type 'GF__Form'. Source: document 'GravityFormComponent' file: 'GraphQL request'`
- `Unknown field 'captchaTheme' on type 'GF__FormFormFields'.`

Removing these fields fixes everything for me. Am I missing something? I can't find these fields in your other plugin (which is awesome, btw) `gatsby-source-gravityforms`, so it makes me think that my version of Gravity Forms is missing some fields in the API.

I'm running the latest version of Gravity Forms (2.4.17.17) and the latest versions of both of your plugins.

**Comment by CalebBarnes** [comment]
I had this same issue. Instead of using the fragments I just made my own hook and removed those fields.

```
import { useStaticQuery, graphql } from "gatsby"

const useGravityData = () => {
  const { allGfForm } = useStaticQuery(
    graphql`
      query {
        allGfForm {
          edges {
            node {
              formId
              title
              slug
              apiURL
              labelPlacement
              descriptionPlacement
              formFields {
                id
                label
                labelPlacement
                description
                descriptionPlacement
                type
                choices
                content
                errorMessage
                inputMaskValue
                isRequired
                visibility
                cssClass
                placeholder
                size
                defaultValue
                maxLength
              }
              button {
                text
              }
              confirmations {
                id
                name
                isDefault
                type
                message
                url
                queryString
              }
            }
          }
        }
      }
    `
  )
  return allGfForm
}

export default useGravityData
```

**Comment by robmarshall** [comment]
I have merged your PR - thanks for that @adamcurl .

I have also added a comment in the readme explaining custom query's. @CalebBarnes
