### ISSUE TITLE
Failed prop type: Input: prop type `maxLength` is invalid

### ISSUE THREAD

**Issue by avinoamsn** [robmarshall/gatsby-gravityforms-component#26]
Every instance of this component produces the below warning:

```bash
Warning: Failed prop type: Input: prop type `maxLength` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
    in Input (created by FieldBuilder)
    in FieldBuilder (created by GravityFormForm)
    in form (created by GravityFormForm)
    ...
```

Here is a sample instance that consistently produces the warning:

```javascript
<GravityFormForm
	id={1}
	formData={useGravityData()}
	lambda={process.env.GATSBY_LAMBDA_ENDPOINT}
/>
```

This is not a breaking issue. Maybe I am missing something, but this looks like a simple prop discrepancy bug. Documenting it here, but I may visit the code and open a PR if I have time.

**Comment by robmarshall** [comment]
Thanks for documenting. I have found the issue, you were right - it was a discrepancy issue. I have fixed.
