### ISSUE TITLE
Radio and Checkbox Inputs Fail Validation

### ISSUE THREAD

**Issue by StrategyLLC** [robmarshall/gatsby-gravityforms-component#31]
Radio and checkbox inputs that are set to required always fail validation. They are able to pass if and only if all checkboxes and radio buttons are selected. Another issue with the radio buttons is that you can select multiples of them. This goes against the expected user experience.

Versions that i'm running:

"gatsby-source-gravityforms": "^1.0.15"
"gatsby-gravityforms-component": "^2.0.1"

**Comment by robmarshall** [comment]
Radio buttons and checkboxes still need work (see readme for development progress). If you can spare some time to add this functionality it would be greatly appreciated.
