### ISSUE TITLE
Issue with Radio Input fields

### ISSUE THREAD

**Issue by n1cklarosa** [robmarshall/gatsby-gravityforms-component#43]
This component is fantastic and has made life a lot easier, the issue I am having is when using a radio field. The user is able to select multiple options and cannot deselect any options they have clicked on.

I am using the latest gravity forms plugin http://2.5.3.1/ and am using the example component found in the readme. Could I have set something up incorrectly?

Any help would be appreciated.
thanks!

**Comment by robmarshall** [comment]
Hi @n1cklarosa This plugin is a bit outdated and I am currently working on a newer/cleaner version. I am unable to help with any issues currently.
